### ISSUE TITLE
Unrelated, will delete after

### ISSUE THREAD

**Issue by crhowell3** [SimmyPeet/Axis#1]
Hey @Simmypeet, I apologize for making an issue on here that is unrelated to this project, but I just wanted to get in touch to see if you happened to have archived your `pernix-lang` repository. I am trying to learn the basics of compilers, and I found your article from December 2022. I was unable to find your project that you made for the article; do you still have the code? If so, I would love to use it as a reference. 

In any case, I again apologize for the unrelated issue. 

Thanks,

Cameron

**Comment by Simmypeet** [comment]
Thanks for your attention! I've made the `pernix-lang` repository private as it has evolved into something more than a tutorial repository. Luckily, I've made a repository called `flux` in my profile, which happens to be a college project; however, it's an interpreter. I hope this helps!
